#!/usr/bin/env bash
# Setup Zitadel for MCP OAuth testing
# Prerequisites:
#   cd deploy
#   mkdir -p machinekey
#   docker compose -f docker-compose.local-test.yml up -d zitadel-db zitadel
#   # Wait ~30s for Zitadel to initialize
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ZITADEL_URL="http://localhost:8085"
PAT_FILE="$SCRIPT_DIR/machinekey/admin.pat"
ENV_FILE="$SCRIPT_DIR/.env.local-test"

echo "=== Zitadel MCP OAuth Setup ==="
echo ""

# 1. Read admin PAT
if [ ! -f "$PAT_FILE" ]; then
  echo "ERROR: $PAT_FILE not found."
  echo "Make sure Zitadel has been started with ZITADEL_FIRSTINSTANCE_PATPATH."
  exit 1
fi
ADMIN_TOKEN=$(cat "$PAT_FILE")
echo "Using admin PAT from $PAT_FILE"

# 2. Wait for Zitadel
echo "Waiting for Zitadel..."
for i in $(seq 1 30); do
  if curl -sf "$ZITADEL_URL/debug/ready" > /dev/null 2>&1; then
    echo "Zitadel is ready!"
    break
  fi
  if [ "$i" -eq 30 ]; then echo "ERROR: Zitadel not ready"; exit 1; fi
  sleep 2
done

# Helper
api() {
  local method="$1" path="$2"
  shift 2
  curl -sf "$ZITADEL_URL$path" \
    -X "$method" \
    -H "Authorization: Bearer $ADMIN_TOKEN" \
    -H "Content-Type: application/json" \
    "$@"
}

# 3. Create project
echo ""
echo "Creating project 'MCP Server'..."
PROJECT_RESPONSE=$(api POST /management/v1/projects -d '{"name":"MCP Server"}')
PROJECT_ID=$(echo "$PROJECT_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "  Project ID: $PROJECT_ID"

# 4. Create OIDC application (PKCE, for Claude.ai / test clients)
echo ""
echo "Creating OIDC application 'mcp-client'..."
APP_RESPONSE=$(api POST "/management/v1/projects/$PROJECT_ID/apps/oidc" -d '{
  "name": "mcp-client",
  "redirectUris": ["http://localhost:8000/oauth/callback", "https://claude.ai/oauth/callback"],
  "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
  "grantTypes": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"],
  "appType": "OIDC_APP_TYPE_WEB",
  "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",
  "postLogoutRedirectUris": ["http://localhost:8000"],
  "devMode": true
}')
CLIENT_ID=$(echo "$APP_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['clientId'])")
echo "  Client ID: $CLIENT_ID"

# 5. Create API application for token introspection
# NOTE: Zitadel requires an API application (not a machine user secret)
# for token introspection to work correctly.
echo ""
echo "Creating API application 'mcp-introspector' for token introspection..."
INTROSPECT_RESPONSE=$(api POST "/management/v1/projects/$PROJECT_ID/apps/api" -d '{
  "name": "mcp-introspector",
  "authMethodType": "API_AUTH_METHOD_TYPE_BASIC"
}')
INTROSPECT_CLIENT_ID=$(echo "$INTROSPECT_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['clientId'])")
INTROSPECT_CLIENT_SECRET=$(echo "$INTROSPECT_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['clientSecret'])")
echo "  Introspection Client ID: $INTROSPECT_CLIENT_ID"

# 6. Write .env file
echo ""
echo "Writing $ENV_FILE..."
cat > "$ENV_FILE" << EOF
# Generated by setup-zitadel.sh — $(date -Iseconds)
# Zitadel OAuth credentials for local testing

ODOO_API_KEY=${ODOO_API_KEY:-your_odoo_api_key_here}

OAUTH_ISSUER_URL=http://localhost:8085
OAUTH_RESOURCE_SERVER_URL=http://localhost:8000
ZITADEL_INTROSPECTION_URL=http://localhost:8085/oauth/v2/introspect
ZITADEL_CLIENT_ID=${INTROSPECT_CLIENT_ID}
ZITADEL_CLIENT_SECRET=${INTROSPECT_CLIENT_SECRET}

# OIDC client for testing (PKCE, no secret needed)
MCP_OAUTH_CLIENT_ID=${CLIENT_ID}
ZITADEL_PROJECT_ID=${PROJECT_ID}
EOF

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Zitadel UI:      $ZITADEL_URL  (admin@zitadel.localhost / Password1!)"
echo "MCP Client ID:   $CLIENT_ID"
echo "Introspection:   $INTROSPECT_CLIENT_ID"
echo "Env file:        $ENV_FILE"
echo ""
echo "Next steps:"
echo "  1. Edit $ENV_FILE and set ODOO_API_KEY"
echo "  2. Start MCP server:"
echo "     docker compose -f docker-compose.local-test.yml --env-file .env.local-test up mcp-server -d"
echo ""
echo "To get a test token (client credentials):"
echo "  curl -s http://localhost:8085/oauth/v2/token \\"
echo "    --user '$INTROSPECT_CLIENT_ID:$INTROSPECT_CLIENT_SECRET' \\"
echo "    -d 'grant_type=client_credentials&scope=openid urn:zitadel:iam:org:project:id:$PROJECT_ID:aud'"
